ALTER TABLE `controller`
MODIFY DUmon INT,
MODIFY DUegg INT,
MODIFY DUraid INT,
MODIFY DUquest INT,
MODIFY DUinvasion INT,
MODIFY DCmon INT,
MODIFY DCegg INT,
MODIFY DCraid INT,
MODIFY DCquest INT,
MODIFY DCinvasion INT,
MODIFY DWmon INT,
MODIFY DWegg INT,
MODIFY DWraid INT,
MODIFY DWquest INT,
MODIFY DWinvasion INT,
MODIFY TUmon INT,
MODIFY TUegg INT,
MODIFY TUraid INT,
MODIFY TUquest INT,
MODIFY TUinvasion INT,
MODIFY TCmon INT,
MODIFY TCegg INT,
MODIFY TCraid INT,
MODIFY TCquest INT,
MODIFY TCinvasion INT,
MODIFY TGmon INT,
MODIFY TGegg INT,
MODIFY TGraid INT,
MODIFY TGquest INT,
MODIFY TGinvasion INT
;

ALTER TABLE `discord`
MODIFY msgClean INT,
MODIFY msgSend INT,
MODIFY UmsgSend INT,
MODIFY CmsgSend INT,
MODIFY WmsgSend INT
;

ALTER TABLE `telegram`
MODIFY msgClean INT,
MODIFY msgSend INT,
MODIFY UmsgSend INT,
MODIFY CmsgSend INT,
MODIFY GmsgSend INT
;
